let data=[
    {
      id:1,
      image:"/Image/halfshirt.jpg",
      brand:"peter",
      type:"shirt",
      price:"1399",
      stock:"23"
    },
    {
      id:2,
      image:"/Image/jeans.jpg",
      brand:"peter",
      type:"pant",
      price:"1399",
      stock:"23"
    },
    {
      id:3,
      image:"/Image/shirt.jpg",
      brand:"peter",
      type:"shirt",
      price:"1399",
      stock:"23"
    },
    {
      id:4,
      image:"/Image/shirt1.jpg",
      brand:"peter",
      type:"shirt",
      price:"1399",
      stock:"23"
    },
    {
      id:5,
      image:"/Image/trouser.jpg",
      brand:"peter",
      type:"pant",
      price:"1399",
      stock:"23"
    },
    {
      id:6,
      image:"/Image/trouser1.webp",
      brand:"peter",
      type:"pant",
      price:"1399",
      stock:"23"
    },
    {
      id:7,
      image:"/Image/tshirt.webp",
      brand:"peter",
      type:"shirt",
      price:"1399",
      stock:"23"
    },
]

export default data;